<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6454b4816c686',
	'title' => 'Campo Titolo',
	'fields' => array(
		array(
			'key' => 'field_6454b799eda60',
			'label' => 'Immagine di sfondo',
			'name' => 'bg_image',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'message' => 'Visualizzare il titolo con immagine di sfondo?',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_6454b5737f68f',
			'label' => 'Titoletto',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_6454b4e37f68e',
			'label' => 'Stile Titoletto',
			'name' => 'titoletto',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'standard' => 'Standard',
				'uppercase' => 'Tutto Maiuscolo',
				'none' => 'Nessun Titoletto',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
			'allow_custom' => 0,
			'search_placeholder' => '',
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_6454b5887f690',
			'label' => 'Testo Titoletto',
			'name' => 'pre_title_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6454b4e37f68e',
						'operator' => '!=',
						'value' => 'none',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_6454b5c47f691',
			'label' => 'Colore Titoletto',
			'name' => 'pre_title_accent',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'choices' => array(
				'white' => 'Bianco',
				'text' => 'Grigio',
				'titles' => 'Nero',
				'primary' => 'Rosso',
			),
			'default_value' => 'white',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
			'allow_custom' => 0,
			'search_placeholder' => '',
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_6454b6417f692',
			'label' => 'Titolo',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_6454b64a7f693',
			'label' => 'Titolo',
			'name' => 'title',
			'type' => 'textarea',
			'instructions' => 'Inserisci un titolo custom per la pagina, di default verrà visualizzato il titolo della pagina',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'acfe_save_meta' => 0,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'acfe_textarea_code' => 0,
		),
		array(
			'key' => 'field_6454b72d0ff78',
			'label' => 'Colore Titolo',
			'name' => 'title_accent',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'choices' => array(
				'white' => 'Bianco',
				'text' => 'Grigio',
				'titles' => 'Nero',
				'primary' => 'Rosso',
			),
			'default_value' => 'white',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
			'allow_custom' => 0,
			'search_placeholder' => '',
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_6454b6767f694',
			'label' => 'Descrizione',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_6454b6867f695',
			'label' => 'Descrizione',
			'name' => 'description',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Aggiungere descrizione?',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_6454b6ec7f696',
			'label' => 'Inserisci Descrizione',
			'name' => 'descr_text',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6454b6867f695',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_6454ba8039789',
			'label' => 'Colore Descrizione',
			'name' => 'descr_accent',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'choices' => array(
				'white' => 'Bianco',
				'text' => 'Grigio',
				'titles' => 'Nero',
				'primary' => 'Rosso',
			),
			'default_value' => 'white',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
			'allow_custom' => 0,
			'search_placeholder' => '',
			'wpml_cf_preferences' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'balletto.blade.php',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfml_field_group_mode' => 'translation',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'titles' => 'Titles',
	),
	'modified' => 1687518899,
));

endif;