<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_65c36bf42d8d1',
	'title' => 'Spettacoli per le scuole - prima scelta',
	'fields' => array(
		array(
			'key' => 'field_65c36c0aa36a2',
			'label' => 'NOME SPETTACOLO (1)',
			'name' => 'spettacolo_1',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'inserire il nome del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c4f7d9ec004',
			'label' => 'Prima data "Spettacolo 1"',
			'name' => 'prima_data_spettacolo_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c36c2fa36a5',
			'label' => 'Primo Orario "Spettacolo 1"',
			'name' => 'orario_spettacolo_1',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c4f7f4ec005',
			'label' => 'Seconda data "Spettacolo 1"',
			'name' => 'seconda_data_spettacolo_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c36c3ea36a6',
			'label' => 'Secondo Orario "Spettacolo 1"',
			'name' => 'secondo_orario_spettacolo_1',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'inserire il secondo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c4f824ec006',
			'label' => 'Terza data "Spettacolo 1"',
			'name' => 'terza_data_spettacolo_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c36c5ba36a7',
			'label' => 'Terzo orario "Spettacolo 1"',
			'name' => 'terzo_orario_spettacolo_1',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_66f3e770fcc46',
			'label' => 'Quarto orario "Spettacolo 1"',
			'name' => 'quarto_orario_spettacolo_1',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f403f16573d',
			'label' => 'Quarta data "Spettacolo 1"',
			'name' => 'quarta_data_spettacolo_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f404046573e',
			'label' => 'Quinta data "Spettacolo 1"',
			'name' => 'quinta_data_spettacolo_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f404116573f',
			'label' => 'Sesta data "Spettacolo 1"',
			'name' => 'sesta_data_spettacolo_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4042065740',
			'label' => 'Settima data "Spettacolo 1"',
			'name' => 'settima_data_spettacolo_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4042e65741',
			'label' => 'Ottava data "Spettacolo 1"',
			'name' => 'ottava_data_spettacolo_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4043965742',
			'label' => 'Nona data "Spettacolo 1"',
			'name' => 'nona_data_spettacolo_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4044465743',
			'label' => 'Decima data "Spettacolo 1"',
			'name' => 'decima_data_spettacolo_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4045265744',
			'label' => 'Undicesima data "Spettacolo 1"',
			'name' => 'undicesima_data_spettacolo_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c36c19a36a3',
			'label' => 'NOME SPETTACOLO (2)',
			'name' => 'spettacolo_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c4fecad5103',
			'label' => 'Prima data "Spettacolo 2"',
			'name' => 'prima_data_spettacolo_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c36c6ba36a8',
			'label' => 'Primo orario "Spettacolo 2"',
			'name' => 'primo_orario_spettacolo_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il primo orario per lo spettacolo 2',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c4fef1d5104',
			'label' => 'Seconda data "Spettacolo 2"',
			'name' => 'seconda_data_spettacolo_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c36c7ba36a9',
			'label' => 'Secondo orario "Spettacolo 2"',
			'name' => 'secondo_orario_spettacolo_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c4ff08d5105',
			'label' => 'Terza data "Spettacolo 2"',
			'name' => 'terza_data_spettacolo_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c4ef3733b95',
			'label' => 'Terzo orario "Spettacolo 2"',
			'name' => 'terzo_orario_spettacolo_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_66f4046765745',
			'label' => 'Quarta data "Spettacolo 2"',
			'name' => 'quarta_data_spettacolo_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f3e786fcc47',
			'label' => 'Quarto orario "Spettacolo 2"',
			'name' => 'quarto_orario_spettacolo_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f404e965754',
			'label' => 'Quinta data "Spettacolo 2"',
			'name' => 'quinta_data_spettacolo_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4047065747',
			'label' => 'Sesta data "Spettacolo 2"',
			'name' => 'sesta_data_spettacolo_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4047565748',
			'label' => 'Settima data "Spettacolo 2"',
			'name' => 'settima_data_spettacolo_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4047b65749',
			'label' => 'Ottava data "Spettacolo 2"',
			'name' => 'ottava_data_spettacolo_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f404816574a',
			'label' => 'Nona data "Spettacolo 2"',
			'name' => 'nona_data_spettacolo_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f404836574b',
			'label' => 'Decima data "Spettacolo 2"',
			'name' => 'decima_data_spettacolo_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f404876574c',
			'label' => 'Undicesima data "Spettacolo 2"',
			'name' => 'undicesima_data_spettacolo_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c4ee9933b92',
			'label' => 'NOME SPETTACOLO (3)',
			'name' => 'spettacolo_3',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c4ff1dd5106',
			'label' => 'Prima data "Spettacolo 3"',
			'name' => 'prima_data_spettacolo_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c4ef0233b94',
			'label' => 'Primo orario "Spettacolo 3"',
			'name' => 'primo_orario_spettacolo_3',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c4ff2bd5107',
			'label' => 'Seconda data "Spettacolo 3"',
			'name' => 'seconda_data_spettacolo_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c4ef5b33b96',
			'label' => 'Secondo orario "Spettacolo 3"',
			'name' => 'secondo_orario_spettacolo_3',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c4ff42d5108',
			'label' => 'Terza data "Spettacolo 3"',
			'name' => 'terza_data_spettacolo_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c4ebba5c867',
			'label' => 'Terzo orario "Spettacolo 3"',
			'name' => 'terzo_orario_spettacolo_3',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_66f404936574d',
			'label' => 'Quarta data "Spettacolo 3"',
			'name' => 'quarta_data_spettacolo_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f3e798fcc48',
			'label' => 'Quarto orario "Spettacolo 3"',
			'name' => 'quarto_orario_spettacolo_3',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f404ec65755',
			'label' => 'Quinta data "Spettacolo 3"',
			'name' => 'quinta_data_spettacolo_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4050865757',
			'label' => 'Sesta data "Spettacolo 3"',
			'name' => 'sesta_data_spettacolo_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4051165759',
			'label' => 'Settima data "Spettacolo 3"',
			'name' => 'settima_data_spettacolo_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f405186575b',
			'label' => 'Ottava data "Spettacolo 3"',
			'name' => 'ottava_data_spettacolo_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4051e6575d',
			'label' => 'Nona data "Spettacolo 3"',
			'name' => 'nona_data_spettacolo_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f405256575f',
			'label' => 'Decima data "Spettacolo 3"',
			'name' => 'decima_data_spettacolo_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4052d65761',
			'label' => 'Undicesima data "Spettacolo 3"',
			'name' => 'undicesima_data_spettacolo_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e993aee2150',
			'label' => 'NOME SPETTACOLO (4)',
			'name' => 'spettacolo_4',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e993bce2151',
			'label' => 'Prima data "Spettacolo 4"',
			'name' => 'prima_data_spettacolo_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e993c7e2152',
			'label' => 'Primo orario "Spettacolo 4"',
			'name' => 'primo_orario_spettacolo_4',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e993f2e215b',
			'label' => 'Seconda data "Spettacolo 4"',
			'name' => 'seconda_data_spettacolo_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e993cfe2154',
			'label' => 'Secondo orario "Spettacolo 4"',
			'name' => 'secondo_orario_spettacolo_4',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e993d2e2155',
			'label' => 'Terza data "Spettacolo 4"',
			'name' => 'terza_data_spettacolo_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e993d7e2156',
			'label' => 'Terzo orario "Spettacolo 4"',
			'name' => 'terzo_orario_spettacolo_4',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f404976574e',
			'label' => 'Quarta data "Spettacolo 4"',
			'name' => 'quarta_data_spettacolo_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f3e7a9fcc49',
			'label' => 'Quarto orario "Spettacolo 4"',
			'name' => 'quarto_orario_spettacolo_4',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f404ee65756',
			'label' => 'Quinta data "Spettacolo 4"',
			'name' => 'quinta_data_spettacolo_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4050b65758',
			'label' => 'Sesta data "Spettacolo 4"',
			'name' => 'sesta_data_spettacolo_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f405146575a',
			'label' => 'Settima data "Spettacolo 4"',
			'name' => 'settima_data_spettacolo_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4051b6575c',
			'label' => 'Ottava data "Spettacolo 4"',
			'name' => 'ottava_data_spettacolo_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f405216575e',
			'label' => 'Nona data "Spettacolo 4"',
			'name' => 'nona_data_spettacolo_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4052965760',
			'label' => 'Decima data "Spettacolo 4"',
			'name' => 'decima_data_spettacolo_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4053265762',
			'label' => 'Undicesima data "Spettacolo 4"',
			'name' => 'undicesima_data_spettacolo_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e99447e2166',
			'label' => 'NOME SPETTACOLO (5)',
			'name' => 'spettacolo_5',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9945be216d',
			'label' => 'Prima data "Spettacolo 5"',
			'name' => 'prima_data_spettacolo_5',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e993e1e2157',
			'label' => 'Primo orario "Spettacolo 5"',
			'name' => 'primo_orario_spettacolo_5',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99401e215f',
			'label' => 'Seconda data "Spettacolo 5"',
			'name' => 'seconda_data_spettacolo_5',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994aae2174',
			'label' => 'Secondo orario "Spettacolo 5"',
			'name' => 'secondo_orario_spettacolo_5',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e994c0e217b',
			'label' => 'Terza data "Spettacolo 5"',
			'name' => 'terza_data_spettacolo_5',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994e1e2183',
			'label' => 'Terzo orario "Spettacolo 5"',
			'name' => 'terzo_orario_spettacolo_5',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe731c67e9c',
			'label' => 'quarto orario "Spettacolo 5"',
			'name' => 'quarto_orario_spettacolo_5',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99449e2167',
			'label' => 'NOME SPETTACOLO (6)',
			'name' => 'spettacolo_6',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9945ee216e',
			'label' => 'Prima data "Spettacolo 6"',
			'name' => 'prima_data_spettacolo_6',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e993e8e2158',
			'label' => 'Primo orario "Spettacolo 6"',
			'name' => 'primo_orario_spettacolo_6',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99409e2160',
			'label' => 'Seconda data "Spettacolo 6"',
			'name' => 'seconda_data_spettacolo_6',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994abe2175',
			'label' => 'Secondo orario "Spettacolo 6"',
			'name' => 'secondo_orario_spettacolo_6',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e994c4e217c',
			'label' => 'Terza data "Spettacolo 6"',
			'name' => 'terza_data_spettacolo_6',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994e2e2184',
			'label' => 'Terzo orario "Spettacolo 6"',
			'name' => 'terzo_orario_spettacolo_6',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe733367e9d',
			'label' => 'Quarto orario "Spettacolo 6"',
			'name' => 'quarto_orario_spettacolo_6',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9944ce2168',
			'label' => 'NOME SPETTACOLO (7)',
			'name' => 'spettacolo_7',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99463e216f',
			'label' => 'Prima data "Spettacolo 7"',
			'name' => 'prima_data_spettacolo_7',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e993ece2159',
			'label' => 'Primo orario "Spettacolo 7"',
			'name' => 'primo_orario_spettacolo_7',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9940ce2161',
			'label' => 'Seconda data "Spettacolo 7"',
			'name' => 'seconda_data_spettacolo_7',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994aee2176',
			'label' => 'Secondo orario "Spettacolo 7"',
			'name' => 'secondo_orario_spettacolo_7',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e994c6e217d',
			'label' => 'Terza data "Spettacolo 7"',
			'name' => 'terza_data_spettacolo_7',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994e4e2185',
			'label' => 'Terzo orario "Spettacolo 7"',
			'name' => 'terzo_orario_spettacolo_7',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe734467e9e',
			'label' => 'quarto orario "Spettacolo 7"',
			'name' => 'quarto_orario_spettacolo_7',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9944fe2169',
			'label' => 'NOME SPETTACOLO (8)',
			'name' => 'spettacolo_8',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99465e2170',
			'label' => 'Prima data "Spettacolo 8"',
			'name' => 'prima_data_spettacolo_8',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e993efe215a',
			'label' => 'Primo orario "Spettacolo 8"',
			'name' => 'primo_orario_spettacolo_8',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9940ee2162',
			'label' => 'Seconda data "Spettacolo 8"',
			'name' => 'seconda_data_spettacolo_8',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994b0e2177',
			'label' => 'Secondo orario "Spettacolo 8"',
			'name' => 'secondo_orario_spettacolo_8',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e994c8e217e',
			'label' => 'Terza data "Spettacolo 8"',
			'name' => 'terza_data_spettacolo_8',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994e7e2186',
			'label' => 'Terzo orario "Spettacolo 8"',
			'name' => 'terzo_orario_spettacolo_8',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe735767e9f',
			'label' => 'Quarto orario "Spettacolo 8"',
			'name' => 'quarto_orario_spettacolo_8',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99452e216a',
			'label' => 'NOME SPETTACOLO (9)',
			'name' => 'spettacolo_9',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99466e2171',
			'label' => 'Prima data "Spettacolo 9"',
			'name' => 'prima_data_spettacolo_9',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e993f5e215c',
			'label' => 'Primo orario "Spettacolo 9"',
			'name' => 'primo_orario_spettacolo_9',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99410e2163',
			'label' => 'Seconda data "Spettacolo 9"',
			'name' => 'seconda_data_spettacolo_9',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994b3e2178',
			'label' => 'Secondo orario "Spettacolo 9"',
			'name' => 'secondo_orario_spettacolo_9',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e994cce217f',
			'label' => 'Terza data "Spettacolo 9"',
			'name' => 'terza_data_spettacolo_9',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994e9e2187',
			'label' => 'Terzo orario "Spettacolo 9"',
			'name' => 'terzo_orario_spettacolo_9',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe736767ea0',
			'label' => 'Quarto orario "Spettacolo 9"',
			'name' => 'quarto_orario_spettacolo_9',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99454e216b',
			'label' => 'NOME SPETTACOLO (10)',
			'name' => 'spettacolo_10',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9946be2172',
			'label' => 'Prima data "Spettacolo 10"',
			'name' => 'prima_data_spettacolo_10',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e993f8e215d',
			'label' => 'Primo orario "Spettacolo 10"',
			'name' => 'primo_orario_spettacolo_10',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99413e2164',
			'label' => 'Seconda data "Spettacolo 10"',
			'name' => 'seconda_data_spettacolo_10',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994b5e2179',
			'label' => 'Secondo orario "Spettacolo 10"',
			'name' => 'secondo_orario_spettacolo_10',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e994cee2180',
			'label' => 'Terza data "Spettacolo 10"',
			'name' => 'terza_data_spettacolo_10',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994eae2188',
			'label' => 'Terzo orario "Spettacolo 10"',
			'name' => 'terzo_orario_spettacolo_10',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe737767ea1',
			'label' => 'Quarto orario "Spettacolo 10"',
			'name' => 'quarto_orario_spettacolo_10',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99457e216c',
			'label' => 'NOME SPETTACOLO (11)',
			'name' => 'spettacolo_11',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9946ee2173',
			'label' => 'Prima data "Spettacolo 11"',
			'name' => 'prima_data_spettacolo_11',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e993fce215e',
			'label' => 'Primo orario "Spettacolo 11"',
			'name' => 'primo_orario_spettacolo_11',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99416e2165',
			'label' => 'Seconda data "Spettacolo 11"',
			'name' => 'seconda_data_spettacolo_11',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994b9e217a',
			'label' => 'Secondo orario "Spettacolo 11"',
			'name' => 'secondo_orario_spettacolo_11',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e994d1e2181',
			'label' => 'Terza data "Spettacolo 11"',
			'name' => 'terza_data_spettacolo_11',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e994ece2189',
			'label' => 'Terzo orario "Spettacolo 11"',
			'name' => 'terzo_orario_spettacolo_11',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe738867ea2',
			'label' => 'Quarto orario "Spettacolo 11"',
			'name' => 'quarto_orario_spettacolo_11',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfml_field_group_mode' => 'translation',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1729698036,
));

endif;