<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6720e5621b4f6',
	'title' => 'Spettacoli per le scuole',
	'fields' => array(
		array(
			'key' => 'field_6720e562415d2',
			'label' => 'Spettacoli',
			'name' => 'spettacoli_scuole',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => 'field_6720e7c8415d3',
			'button_label' => 'Aggiungi Spettacolo',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6720e7c8415d3',
					'label' => 'Nome spettacolo',
					'name' => 'nome_spettacolo',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'wpml_cf_preferences' => 2,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6720e562415d2',
				),
				array(
					'key' => 'field_6720e7e0415d4',
					'label' => 'Date',
					'name' => 'date',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'wpml_cf_preferences' => 1,
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'block',
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Aggiungi Data e ora',
					'rows_per_page' => 20,
					'parent_repeater' => 'field_6720e562415d2',
					'sub_fields' => array(
						array(
							'key' => 'field_6720e7fd415d5',
							'label' => 'Data',
							'name' => 'data',
							'aria-label' => '',
							'type' => 'date_picker',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '49',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 1,
							'display_format' => 'd/m/Y',
							'return_format' => 'd/m/Y',
							'first_day' => 1,
							'parent_repeater' => 'field_6720e7e0415d4',
						),
						array(
							'key' => 'field_6720e96803a4f',
							'label' => 'Orari',
							'name' => 'orari',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => 'Inserisci tutti gli orari disponibili separati da virgola e spazio. ES: 10:00, 11:30',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '49',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => 'h',
							'append' => '',
							'parent_repeater' => 'field_6720e7e0415d4',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '5267',
			),
		),
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '5322',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => 'Spettacoli scuole',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfml_field_group_mode' => 'translation',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'templates' => 'Templates',
	),
	'modified' => 1730210578,
));

endif;