<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_64523be1940cb',
	'title' => 'Campi Educational',
	'fields' => array(
		array(
			'key' => 'field_64523bf510799',
			'label' => 'Pagina Lista',
			'name' => 'is_list',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Questa è la pagina Educational principale?',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_645243123047a',
			'label' => 'Breve descrizione',
			'name' => 'breve_descrizione',
			'type' => 'textarea',
			'instructions' => 'Inserisci una descrizione di questa pagina da mostrare nella pagina di lista',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64523bf510799',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_650acb47e0c2e',
			'label' => 'Form prenotazione spettacoli',
			'name' => 'form_prenotazione',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 1,
			'acfe_save_meta' => 0,
			'message' => 'Inserire in questa pagina il form di prenotazione spettacoli?',
			'default_value' => 0,
			'ui' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_650acd27ce717',
			'label' => 'Titolo form',
			'name' => 'titolo_form',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_650acb47e0c2e',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 0,
			'acfe_save_meta' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'educational.blade.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_permissions' => '',
	'acfml_field_group_mode' => 'translation',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'templates' => 'Templates',
	),
	'modified' => 1695206708,
));

endif;