<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_644a2f064dcf6',
	'title' => 'Campi Templates',
	'fields' => array(
		array(
			'key' => 'field_644a2f4816638',
			'label' => 'Sezione Staff',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_644a2f5d16639',
			'label' => 'Membri staff',
			'name' => 'membri_staff',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'wpml_cf_preferences' => 1,
			'sub_fields' => array(
				array(
					'key' => 'field_644a2f891663a',
					'label' => 'Ruolo',
					'name' => 'ruolo',
					'type' => 'text',
					'instructions' => 'Inserisci un ruolo per il membro dello staff',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'wpml_cf_preferences' => 2,
				),
				array(
					'key' => 'field_644a2fb11663b',
					'label' => 'Nome Cognome',
					'name' => 'nome_cognome',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'wpml_cf_preferences' => 2,
				),
			),
		),
		array(
			'key' => 'field_644a2fc11663c',
			'label' => 'Descrizione',
			'name' => 'descrizione',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_644a2fe21663d',
			'label' => 'Cast',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_644a3203756d8',
			'label' => 'Titolo sezione',
			'name' => 'titolo_sezione',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_644a3212756d9',
			'label' => 'Descrizione sezione',
			'name' => 'descrizione_sezione',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_644a2ff61663e',
			'label' => 'Modalità',
			'name' => 'modalita',
			'type' => 'select',
			'instructions' => 'Scegli il tipo di visualizzazione del casting',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'list' => 'Lista con link	"Mostra tutto"',
				'slide' => 'Slider',
				'toggle' => 'Fisarmonica',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
			'allow_custom' => 0,
			'search_placeholder' => '',
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_644a30531663f',
			'label' => 'Membri Cast',
			'name' => 'membri_cast',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'wpml_cf_preferences' => 1,
			'sub_fields' => array(
				array(
					'key' => 'field_644a324c11440',
					'label' => 'Foto',
					'name' => 'foto',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_644a2ff61663e',
								'operator' => '==',
								'value' => 'list',
							),
						),
						array(
							array(
								'field' => 'field_644a2ff61663e',
								'operator' => '==',
								'value' => 'slide',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'uploader' => '',
					'acfe_thumbnail' => 0,
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'library' => 'all',
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_644a305316641',
					'label' => 'Nome',
					'name' => 'nome',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'wpml_cf_preferences' => 2,
					'acfe_save_meta' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
				),
				array(
					'key' => 'field_649ecdfe2f5c9',
					'label' => 'Cognome',
					'name' => 'cognome',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'wpml_cf_preferences' => 2,
					'acfe_save_meta' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
				),
				array(
					'key' => 'field_644a305316640',
					'label' => 'Ruolo',
					'name' => 'ruolo',
					'type' => 'text',
					'instructions' => 'Inserisci un ruolo per il membro dello staff',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_644a2ff61663e',
								'operator' => '==',
								'value' => 'slide',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'wpml_cf_preferences' => 2,
				),
				array(
					'key' => 'field_644a30a516642',
					'label' => 'Bio',
					'name' => 'bio',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_644a2ff61663e',
								'operator' => '==',
								'value' => 'list',
							),
						),
						array(
							array(
								'field' => 'field_644a2ff61663e',
								'operator' => '==',
								'value' => 'toggle',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
					'acfe_textarea_code' => 0,
					'wpml_cf_preferences' => 2,
				),
				array(
					'key' => 'field_6454c4f3679b3',
					'label' => 'Social',
					'name' => 'social',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_repeater_stylised_button' => 0,
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Aggingi profilo social',
					'acfe_settings' => '',
					'wpml_cf_preferences' => 1,
					'sub_fields' => array(
						array(
							'key' => 'field_6454c500679b4',
							'label' => 'Social',
							'name' => 'social',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'instagram' => 'instagram',
								'facebook' => 'facebook',
								'twitter' => 'twitter',
								'linkedin' => 'linkedin',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'acfe_settings' => '',
							'acfe_validate' => '',
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
							'wpml_cf_preferences' => 1,
						),
						array(
							'key' => 'field_6454c520679b5',
							'label' => 'Link Social',
							'name' => 'link_social',
							'type' => 'url',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'acfe_settings' => '',
							'acfe_validate' => '',
							'wpml_cf_preferences' => 1,
						),
					),
				),
			),
		),
		array(
			'key' => 'field_644a30f616645',
			'label' => 'Testo contenuto',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_644a311516646',
			'label' => 'Testo',
			'name' => 'testo',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
			'wpml_cf_preferences' => 2,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'balletto.blade.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'discussion',
		2 => 'comments',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_permissions' => '',
	'acfml_field_group_mode' => 'translation',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'templates' => 'Templates',
	),
	'modified' => 1688129043,
));

endif;