<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6462259334689',
	'title' => 'Tabelle',
	'fields' => array(
		array(
			'key' => 'field_646225b897e67',
			'label' => 'Tabella 1',
			'name' => 'tabella_1',
			'type' => 'dynamic_table',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 2,
			'tableclass' => 'no-more-tables',
			'maxrows' => '',
			'disable_sort' => 0,
			'fixed_columns' => 0,
			'default_headers' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'default_header' => '',
			'readonly' => 0,
			'disabled' => 0,
			'sub_fields' => array(
			),
		),
		array(
			'key' => 'field_646226831d22c',
			'label' => 'Tabella 2',
			'name' => 'tabella_2',
			'type' => 'dynamic_table',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 2,
			'tableclass' => 'no-more-tables',
			'maxrows' => '',
			'disable_sort' => 0,
			'fixed_columns' => 0,
			'default_headers' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'default_header' => '',
			'readonly' => 0,
			'disabled' => 0,
			'sub_fields' => array(
			),
		),
		array(
			'key' => 'field_646226851d22d',
			'label' => 'Tabella 3',
			'name' => 'tabella_3',
			'type' => 'dynamic_table',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 2,
			'tableclass' => 'no-more-tables',
			'maxrows' => '',
			'disable_sort' => 0,
			'fixed_columns' => 0,
			'default_headers' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'default_header' => '',
			'readonly' => 0,
			'disabled' => 0,
			'sub_fields' => array(
			),
		),
		array(
			'key' => 'field_646226861d22e',
			'label' => 'Tabella 4',
			'name' => 'tabella_4',
			'type' => 'dynamic_table',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 2,
			'tableclass' => 'no-more-tables',
			'maxrows' => '',
			'disable_sort' => 0,
			'fixed_columns' => 0,
			'default_headers' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'default_header' => '',
			'readonly' => 0,
			'disabled' => 0,
			'sub_fields' => array(
			),
		),
		array(
			'key' => 'field_64b6727999cab',
			'label' => 'Tabella 5',
			'name' => 'tabella_5',
			'type' => 'dynamic_table',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 2,
			'acfe_save_meta' => 0,
			'tableclass' => 'no-more-tables',
			'maxrows' => '',
			'disable_sort' => 0,
			'fixed_columns' => 0,
			'default_headers' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'default_header' => '',
			'readonly' => 0,
			'disabled' => 0,
			'sub_fields' => array(
			),
		),
		array(
			'key' => 'field_64b6728399cac',
			'label' => 'Tabella 6',
			'name' => 'tabella_6',
			'type' => 'dynamic_table',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 2,
			'acfe_save_meta' => 0,
			'tableclass' => 'no-more-tables',
			'maxrows' => '',
			'disable_sort' => 0,
			'fixed_columns' => 0,
			'default_headers' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'default_header' => '',
			'readonly' => 0,
			'disabled' => 0,
			'sub_fields' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_permissions' => '',
	'acfml_field_group_mode' => 'translation',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'pages' => 'Pages',
	),
	'modified' => 1694764846,
));

endif;