<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_62cfd36354787',
	'title' => 'Opzioni Generali',
	'fields' => array(
		array(
			'key' => 'field_62de93d6fd45b',
			'label' => 'Dati azienda',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_62de97a9fd45d',
			'label' => 'Partita IVA',
			'name' => 'p_iva',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_62cfd409f40a1',
			'label' => 'Social',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_62cfd415f40a2',
			'label' => 'Social',
			'name' => 'social',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Aggiungi social',
			'wpml_cf_preferences' => 1,
			'sub_fields' => array(
				array(
					'key' => 'field_62cfd450f40a3',
					'label' => 'Tipo social',
					'name' => 'tipo_social',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'facebook' => 'Facebook',
						'instagram' => 'Instagram',
						'twitter' => 'Twitter',
						'linkedin' => 'Linkedin',
						'youtube' => 'YouTube',
						'tiktok' => 'TikTok',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
					'allow_custom' => 0,
					'search_placeholder' => '',
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_62cfd8d4f40a4',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'wpml_cf_preferences' => 1,
				),
			),
		),
		array(
			'key' => 'field_62cfd393f409f',
			'label' => 'Testi Footer',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_62cfd3b5f40a0',
			'label' => 'Testo sezione Newsletter',
			'name' => 'newsletter_text',
			'type' => 'textarea',
			'instructions' => 'Inserire del testo di introduzione alla Newsletter nel footer',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'acfe_textarea_code' => 0,
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_643fbfd1706f4',
			'label' => 'Testi CTA Spettacoli',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_649ec91190fd5',
			'label' => 'Testi modalità d\'acquisto',
			'name' => 'testi_modalita_dacquisto',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
		),
		array(
			'key' => 'field_643fc00a706f6',
			'label' => 'Immagine di sfondo della sezione',
			'name' => 'spettacoli_cta_bg',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'acfe_thumbnail' => 0,
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'library' => 'all',
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_643fbfea706f5',
			'label' => 'Titoletto',
			'name' => 'spettacoli_cta_titoletto',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_643fc02b706f7',
			'label' => 'Titolo',
			'name' => 'spettacoli_cta_titolo',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'acfe_textarea_code' => 0,
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_6449092801021',
			'label' => 'Link Pagine principali',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_6449093d01022',
			'label' => 'Pagina tutti gli eventi',
			'name' => 'eventi_page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => '',
			'taxonomy' => '',
			'allow_null' => 0,
			'allow_archives' => 1,
			'multiple' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_644a56c492696',
			'label' => 'Varie',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_644a56d292697',
			'label' => 'Immagine placeholder per casting',
			'name' => 'cast_placeholder',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'uploader' => '',
			'return_format' => 'url',
			'preview_size' => 'medium',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_thumbnail' => 0,
			'library' => 'all',
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_6454a647d876f',
			'label' => 'Immagine placeholder per i titoli di pagina',
			'name' => 'title_placeholder',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'uploader' => '',
			'return_format' => 'url',
			'preview_size' => 'medium',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_thumbnail' => 0,
			'library' => 'all',
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_64553f20e40f4',
			'label' => 'Immagine placeholder per gli articoli',
			'name' => 'post_placeholder',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 1,
			'acfe_save_meta' => 0,
			'uploader' => '',
			'return_format' => 'url',
			'preview_size' => 'medium',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'library' => 'all',
		),
		array(
			'key' => 'field_649e8ebd65226',
			'label' => 'Immagine placeholder per gli spettacoli',
			'name' => 'show_placeholder',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 1,
			'acfe_save_meta' => 0,
			'uploader' => '',
			'return_format' => 'url',
			'preview_size' => 'medium',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'library' => 'all',
		),
		array(
			'key' => 'field_646f6437eff8f',
			'label' => 'Titolo pagina Spettacoli ed Eventi',
			'name' => 'titolo_pagina_spettacoli_ed_eventi',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
		),
		array(
			'key' => 'field_632d708ec35f2',
			'label' => 'Header & Footer Scripts',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 1,
		),
		array(
			'key' => 'field_632d70a9c35f3',
			'label' => 'Head scripts',
			'name' => 'head_scripts',
			'type' => 'acfe_code_editor',
			'instructions' => 'Inserisci qui il codice da immettere dentro i tag "head"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'mode' => 'text/html',
			'lines' => 1,
			'indent_unit' => 4,
			'maxlength' => '',
			'rows' => 4,
			'max_rows' => '',
			'return_entities' => 0,
			'return_format' => array(
			),
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_632d711ec35f4',
			'label' => 'Body scripts (start)',
			'name' => 'body_start_scripts',
			'type' => 'acfe_code_editor',
			'instructions' => 'Inserisci qui il codice da immettere subito dopo il tag "body"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'mode' => 'text/html',
			'lines' => 1,
			'indent_unit' => 4,
			'maxlength' => '',
			'rows' => 4,
			'max_rows' => '',
			'return_entities' => 0,
			'return_format' => array(
			),
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_632d715fc35f5',
			'label' => 'Body scripts (end)',
			'name' => 'body_end_scripts',
			'type' => 'acfe_code_editor',
			'instructions' => 'Inserisci qui il codice da immettere subito prima del tag " /body"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'mode' => 'text/html',
			'lines' => 1,
			'indent_unit' => 4,
			'maxlength' => '',
			'rows' => 4,
			'max_rows' => '',
			'return_entities' => 0,
			'return_format' => array(
			),
			'wpml_cf_preferences' => 2,
		),
		array(
			'key' => 'field_65117d410cf14',
			'label' => 'Destinatari email',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 0,
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_65117d4f0cf15',
			'label' => 'Form Rimborsi',
			'name' => 'form_rimborsi',
			'type' => 'text',
			'instructions' => 'inserire gli indirizzi email separati da una virgola',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 0,
			'acfe_save_meta' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
		),
		array(
			'key' => 'field_65117d5d0cf16',
			'label' => 'Form Prenotazione scuole',
			'name' => 'form_prenotazione_scuole',
			'type' => 'text',
			'instructions' => 'inserire gli indirizzi email separati da una virgola',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'wpml_cf_preferences' => 0,
			'acfe_save_meta' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'opzioni-tema',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_permissions' => '',
	'acfml_field_group_mode' => 'translation',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'general' => 'General',
	),
	'modified' => 1695645035,
));

endif;