<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_65c6488675f97',
	'title' => 'Spettacoli per le scuole - seconda scelta',
	'fields' => array(
		array(
			'key' => 'field_65c6488694e19',
			'label' => 'NOME SPETTACOLO (1)',
			'name' => 'spettacolo_1_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'inserire il nome del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c6488694e71',
			'label' => 'Prima data "Spettacolo 1"',
			'name' => 'prima_data_spettacolo_1_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c6488694ec5',
			'label' => 'Primo Orario "Spettacolo 1"',
			'name' => 'orario_spettacolo_1_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c6488694f17',
			'label' => 'Seconda data "Spettacolo 1"',
			'name' => 'seconda_data_spettacolo_1_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c6488694f52',
			'label' => 'Secondo Orario "Spettacolo 1"',
			'name' => 'secondo_orario_spettacolo_1_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'inserire il secondo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c6488694fcc',
			'label' => 'Terza data "Spettacolo 1"',
			'name' => 'terza_data_spettacolo_1_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c6488695017',
			'label' => 'Terzo orario "Spettacolo 1"',
			'name' => 'terzo_orario_spettacolo_1_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_66f41fc9c91c4',
			'label' => 'Quarta data "Spettacolo 1"',
			'name' => 'quarta_data_spettacolo_1_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f42001c91c6',
			'label' => 'Quarto orario "Spettacolo 1"',
			'name' => 'quarto_orario_spettacolo_1_1',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f41fe0c91c5',
			'label' => 'Quinta data "Spettacolo 1"',
			'name' => 'quinta_data_spettacolo_1_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f42014c91c7',
			'label' => 'Sesta data "Spettacolo 1"',
			'name' => 'sesta_data_spettacolo_1_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f42026c91c8',
			'label' => 'Settima data "Spettacolo 1"',
			'name' => 'settima_data_spettacolo_1_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f42038c91c9',
			'label' => 'Ottava data "Spettacolo 1"',
			'name' => 'ottava_data_spettacolo_1_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f42046c91ca',
			'label' => 'Nona data "Spettacolo 1"',
			'name' => 'nona_data_spettacolo_1_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f42053c91cb',
			'label' => 'Decima data "Spettacolo 1"',
			'name' => 'decima_data_spettacolo_1_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f42063c91cc',
			'label' => 'Undicesima data "Spettacolo 1"',
			'name' => 'undicesima_data_spettacolo_1_1',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c648869505f',
			'label' => 'NOME SPETTACOLO (2)',
			'name' => 'spettacolo_2_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c64886950ad',
			'label' => 'Prima data "Spettacolo 2"',
			'name' => 'prima_data_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c64886950f8',
			'label' => 'Primo orario "Spettacolo 2"',
			'name' => 'primo_orario_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il primo orario per lo spettacolo 2',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c648869513f',
			'label' => 'Seconda data "Spettacolo 2"',
			'name' => 'seconda_data_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c6488695187',
			'label' => 'Secondo orario "Spettacolo 2"',
			'name' => 'secondo_orario_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c64886951cf',
			'label' => 'Terza data "Spettacolo 2"',
			'name' => 'terza_data_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c6488695217',
			'label' => 'Terzo orario "Spettacolo 2"',
			'name' => 'terzo_orario_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_66f42078c91cd',
			'label' => 'Quarta data "Spettacolo 2"',
			'name' => 'quarta_data_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4208fc91ce',
			'label' => 'Quarto orario "Spettacolo 2"',
			'name' => 'quarto_orario_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f420a4c91cf',
			'label' => 'Quinta data "Spettacolo 2"',
			'name' => 'quinta_data_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f420b8c91d0',
			'label' => 'Sesta data "Spettacolo 2"',
			'name' => 'sesta_data_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f420c5c91d1',
			'label' => 'Settima data "Spettacolo 2"',
			'name' => 'settima_data_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f42380ad76d',
			'label' => 'Ottava data "Spettacolo 2"',
			'name' => 'ottava_data_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4238dad76e',
			'label' => 'Nona data "Spettacolo 2"',
			'name' => 'nona_data_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f42398ad76f',
			'label' => 'Decima data "Spettacolo 2"',
			'name' => 'decima_data_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f423a7ad770',
			'label' => 'Undicesima data "Spettacolo 2"',
			'name' => 'undicesima_data_spettacolo_2_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e995403ffa4',
			'label' => 'NOME SPETTACOLO (3)',
			'name' => 'spettacolo_3_3',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_65c64886952a6',
			'label' => 'Prima data "Spettacolo 3"',
			'name' => 'prima_data_spettacolo_3_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c64886952ee',
			'label' => 'Primo orario "Spettacolo 3"',
			'name' => 'primo_orario_spettacolo_3_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c6488695332',
			'label' => 'Seconda data "Spettacolo 3"',
			'name' => 'seconda_data_spettacolo_3_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c6488695383',
			'label' => 'Secondo orario "Spettacolo 3"',
			'name' => 'secondo_orario_spettacolo_3_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_65c64886953cb',
			'label' => 'Terza data "Spettacolo 3"',
			'name' => 'terza_data_spettacolo_3_2',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_65c6488695412',
			'label' => 'Terzo orario "Spettacolo 3"',
			'name' => 'terzo_orario_spettacolo_3_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_66f423d417ec2',
			'label' => 'Quarta data "Spettacolo 3"',
			'name' => 'quarta_data_spettacolo_3_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f423e417ec3',
			'label' => 'Quarto orario "Spettacolo 3"',
			'name' => 'quarto_orario_spettacolo_3_3',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f423f817ec4',
			'label' => 'Quinta data "Spettacolo 3"',
			'name' => 'quinta_data_spettacolo_3_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4240f17ec5',
			'label' => 'Sesta data "Spettacolo 3"',
			'name' => 'sesta_data_spettacolo_3_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4241d17ec6',
			'label' => 'Settima data "Spettacolo 3"',
			'name' => 'settima_data_spettacolo_3_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4242d17ec7',
			'label' => 'Ottava data "Spettacolo 3"',
			'name' => 'ottava_data_spettacolo_3_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4243b17ec8',
			'label' => 'Nona data "Spettacolo 3"',
			'name' => 'nona_data_spettacolo_3_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4244917ec9',
			'label' => 'Decima data "Spettacolo 3"',
			'name' => 'decima_data_spettacolo_3_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f4245617eca',
			'label' => 'Undicesima data "Spettacolo 3"',
			'name' => 'undicesima_data_spettacolo_3_3',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e995483ffa6',
			'label' => 'NOME SPETTACOLO (4)',
			'name' => 'spettacolo_4_4',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e995dc3ffb6',
			'label' => 'Prima data "Spettacolo 4"',
			'name' => 'prima_data_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e996013ffb7',
			'label' => 'Primo orario "Spettacolo 4"',
			'name' => 'primo_orario_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9961e3ffb8',
			'label' => 'Seconda data "Spettacolo 4"',
			'name' => 'seconda_data_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e9962f3ffb9',
			'label' => 'Secondo orario "Spettacolo 4"',
			'name' => 'secondo_orario_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e996383ffba',
			'label' => 'Terza data "Spettacolo 4"',
			'name' => 'terza_data_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e996443ffbb',
			'label' => 'Terzo orario "Spettacolo 4"',
			'name' => 'terzo_orario_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f42485d44d8',
			'label' => 'Quarta data "Spettacolo 4"',
			'name' => 'quarta_data_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f42496d44d9',
			'label' => 'Quarto orario "Spettacolo 4"',
			'name' => 'quarto_orario_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f424a8d44da',
			'label' => 'Quinta data "Spettacolo 4"',
			'name' => 'quinta_data_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f424bdd44db',
			'label' => 'Sesta data "Spettacolo 4"',
			'name' => 'sesta_data_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f424c9d44dc',
			'label' => 'Settima data "Spettacolo 4"',
			'name' => 'settima_data_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f424d6d44dd',
			'label' => 'Ottava data "Spettacolo 4"',
			'name' => 'ottava_data_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f424e3d44de',
			'label' => 'Nona data "Spettacolo 4"',
			'name' => 'nona_data_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f424efd44df',
			'label' => 'Decima data "Spettacolo 4"',
			'name' => 'decima_data_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f424fbd44e0',
			'label' => 'Undicesima data "Spettacolo 4"',
			'name' => 'undicesima_data_spettacolo_4_4',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e995523ffa8',
			'label' => 'NOME SPETTACOLO (5)',
			'name' => 'spettacolo_5_5',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e996caa82f7',
			'label' => 'Prima data "Spettacolo 5"',
			'name' => 'prima_data_spettacolo_5_5',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e996d7a82f8',
			'label' => 'Primo orario "Spettacolo 5"',
			'name' => 'primo_orario_spettacolo_5_5',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e996dfa82f9',
			'label' => 'Seconda data "Spettacolo 5"',
			'name' => 'seconda_data_spettacolo_5_5',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e996e6a82fa',
			'label' => 'Secondo orario "Spettacolo 5"',
			'name' => 'secondo_orario_spettacolo_5_5',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e996eda82fb',
			'label' => 'Terza data "Spettacolo 5"',
			'name' => 'terza_data_spettacolo_5_5',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e996f2a82fc',
			'label' => 'Terzo orario "Spettacolo 5"',
			'name' => 'terzo_orario_spettacolo_5_5',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe73e1cec8c',
			'label' => 'Quarto orario "Spettacolo 5"',
			'name' => 'quarto_orario_spettacolo_5_5',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e995583ffaa',
			'label' => 'NOME SPETTACOLO (6)',
			'name' => 'spettacolo_6_6',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e996fba82fd',
			'label' => 'Prima data "Spettacolo 6"',
			'name' => 'prima_data_spettacolo_6_6',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e99704a82fe',
			'label' => 'Primo orario "Spettacolo 6"',
			'name' => 'primo_orario_spettacolo_6_6',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9970ba82ff',
			'label' => 'Seconda data "Spettacolo 6"',
			'name' => 'seconda_data_spettacolo_6_6',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e99711a8300',
			'label' => 'Secondo orario "Spettacolo 6"',
			'name' => 'secondo_orario_spettacolo_6_6',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99717a8301',
			'label' => 'Terza data "Spettacolo 6"',
			'name' => 'terza_data_spettacolo_6_6',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e9971ca8302',
			'label' => 'Terzo orario "Spettacolo 6"',
			'name' => 'terzo_orario_spettacolo_6_6',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe80559a165',
			'label' => 'Quarto orario "Spettacolo 6"',
			'name' => 'quarto_orario_spettacolo_6_6',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9955c3ffac',
			'label' => 'NOME SPETTACOLO (7)',
			'name' => 'spettacolo_7_7',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99726a8303',
			'label' => 'Prima data "Spettacolo 7"',
			'name' => 'prima_data_spettacolo_7_7',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e9972da8304',
			'label' => 'Primo orario "Spettacolo 7"',
			'name' => 'primo_orario_spettacolo_7_7',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99734a8305',
			'label' => 'Seconda data "Spettacolo 7"',
			'name' => 'seconda_data_spettacolo_7_7',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e9973aa8306',
			'label' => 'Secondo orario "Spettacolo 7"',
			'name' => 'secondo_orario_spettacolo_7_7',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99743a8307',
			'label' => 'Terza data "Spettacolo 7"',
			'name' => 'terza_data_spettacolo_7_7',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e99749a8308',
			'label' => 'Terzo orario "Spettacolo 7"',
			'name' => 'terzo_orario_spettacolo_7_7',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe73f2cec8d',
			'label' => 'Quarto orario "Spettacolo 7"',
			'name' => 'quarto_orario_spettacolo_7_7',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e995613ffae',
			'label' => 'NOME SPETTACOLO (8)',
			'name' => 'spettacolo_8_8',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e999b515066',
			'label' => 'Prima data "Spettacolo 8"',
			'name' => 'prima_data_spettacolo_8_8',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e999c015067',
			'label' => 'Primo orario "Spettacolo 8"',
			'name' => 'primo_orario_spettacolo_8_8',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e999c715068',
			'label' => 'Seconda data "Spettacolo 8"',
			'name' => 'seconda_data_spettacolo_8_8',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e999ce15069',
			'label' => 'Secondo orario "Spettacolo 8"',
			'name' => 'secondo_orario_spettacolo_8_8',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e999d51506a',
			'label' => 'Terza data "Spettacolo 8"',
			'name' => 'terza_data_spettacolo_8_8',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e999db1506b',
			'label' => 'Terzo orario "Spettacolo 8"',
			'name' => 'terzo_orario_spettacolo_8_8',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe7404cec8e',
			'label' => 'Quarto orario "Spettacolo 8"',
			'name' => 'quarto_orario_spettacolo_8_8',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e995693ffb0',
			'label' => 'NOME SPETTACOLO (9)',
			'name' => 'spettacolo_9_9',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e999e91506c',
			'label' => 'Prima data "Spettacolo 9"',
			'name' => 'prima_data_spettacolo_9_9',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e999ef1506d',
			'label' => 'Primo orario "Spettacolo 9"',
			'name' => 'primo_orario_spettacolo_9_9',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e999f71506e',
			'label' => 'Seconda data "Spettacolo 9"',
			'name' => 'seconda_data_spettacolo_9_9',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e999fe1506f',
			'label' => 'Secondo orario "Spettacolo 9"',
			'name' => 'secondo_orario_spettacolo_9_9',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e99a0515070',
			'label' => 'Terza data "Spettacolo 9"',
			'name' => 'terza_data_spettacolo_9_9',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66e99a0b15071',
			'label' => 'Terzo orario "Spettacolo 9"',
			'name' => 'terzo_orario_spettacolo_9_9',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe7421cec8f',
			'label' => 'Quarto orario "Spettacolo 10"',
			'name' => 'quarto_orario_spettacolo_9_9',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e9956e3ffb2',
			'label' => 'NOME SPETTACOLO (10)',
			'name' => 'spettacolo_10_10',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f14b5c9cb8f',
			'label' => 'Prima data "Spettacolo 10"',
			'name' => 'prima_data_spettacolo_10_10',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f14b829cb93',
			'label' => 'Primo orario "Spettacolo 10"',
			'name' => 'primo_orario_spettacolo_10_10',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f14b919cb95',
			'label' => 'Seconda data "Spettacolo 10"',
			'name' => 'seconda_data_spettacolo_10_10',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f14b9d9cb97',
			'label' => 'Secondo orario "Spettacolo 10"',
			'name' => 'secondo_orario_spettacolo_10_10',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f14baa9cb99',
			'label' => 'Terza data "Spettacolo 10"',
			'name' => 'terza_data_spettacolo_10_10',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f14bb79cb9b',
			'label' => 'Terzo orario "Spettacolo 10"',
			'name' => 'terzo_orario_spettacolo_10_10',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe742ecec90',
			'label' => 'Quarto orario "Spettacolo 10"',
			'name' => 'quarto_orario_spettacolo_10_10',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66e995723ffb4',
			'label' => 'NOME SPETTACOLO (11)',
			'name' => 'spettacolo_11_11',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il nome del secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f14b6a9cb90',
			'label' => 'Prima data "Spettacolo 11"',
			'name' => 'prima_data_spettacolo_11_11',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f14b8a9cb94',
			'label' => 'Primo orario "Spettacolo 11"',
			'name' => 'primo_orario_spettacolo_11_11',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f14b969cb96',
			'label' => 'Seconda data "Spettacolo 11"',
			'name' => 'seconda_data_spettacolo_11_11',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f14ba29cb98',
			'label' => 'Secondo orario "Spettacolo 11"',
			'name' => 'secondo_orario_spettacolo_11_11',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f14bb09cb9a',
			'label' => 'Terza data "Spettacolo 11"',
			'name' => 'terza_data_spettacolo_11_11',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Inserire il terzo orario del primo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66f14bbc9cb9c',
			'label' => 'Terzo orario "Spettacolo 11"',
			'name' => 'terzo_orario_spettacolo_11_11',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66fe743bcec91',
			'label' => 'Quarto orario "Spettacolo 11"',
			'name' => 'quarto_orario_spettacolo_11_11',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserire il secondo orario per il secondo spettacolo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 2,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfml_field_group_mode' => 'translation',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1729698047,
));

endif;